import { ICountry } from './types';

export const countries: ICountry[] = [
  {
    alpha2: 'AD',
    alpha3: 'AND',
    callingCodes: ['+376'],
    currencies: ['EUR'],
    emoji: '🇦🇩',
    fullName: 'the Principality of Andorra',
    ioc: 'AND',
    languages: [
      {
        alpha2: 'ca',
        alpha3: 'cat',
      },
    ],
    numeric: '020',
    shortName: 'Andorra',
  },
  {
    alpha2: 'AE',
    alpha3: 'ARE',
    callingCodes: ['+971'],
    currencies: ['AED'],
    emoji: '🇦🇪',
    fullName: 'the United Arab Emirates',
    ioc: 'UAE',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '784',
    shortName: 'United Arab Emirates (the)',
  },
  {
    alpha2: 'AF',
    alpha3: 'AFG',
    callingCodes: ['+93'],
    currencies: ['AFN'],
    emoji: '🇦🇫',
    fullName: 'the Islamic Republic of Afghanistan',
    ioc: 'AFG',
    languages: [
      {
        alpha2: 'fa',
        alpha3: 'fas',
      },
      {
        alpha2: 'ps',
        alpha3: 'pus',
      },
    ],
    numeric: '004',
    shortName: 'Afghanistan',
  },
  {
    alpha2: 'AG',
    alpha3: 'ATG',
    callingCodes: ['+1 268'],
    currencies: ['XCD'],
    emoji: '🇦🇬',
    ioc: 'ANT',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '028',
    shortName: 'Antigua and Barbuda',
    territory: 'Redonda Island',
  },
  {
    alpha2: 'AI',
    alpha3: 'AIA',
    callingCodes: ['+1 264'],
    currencies: ['XCD'],
    emoji: '🇦🇮',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '660',
    shortName: 'Anguilla',
  },
  {
    alpha2: 'AL',
    alpha3: 'ALB',
    callingCodes: ['+355'],
    currencies: ['ALL'],
    emoji: '🇦🇱',
    fullName: 'the Republic of Albania',
    ioc: 'ALB',
    languages: [
      {
        alpha2: 'sq',
        alpha3: 'sqi',
      },
    ],
    numeric: '008',
    shortName: 'Albania',
  },
  {
    alpha2: 'AM',
    alpha3: 'ARM',
    callingCodes: ['+374'],
    currencies: ['AMD'],
    emoji: '🇦🇲',
    fullName: 'the Republic of Armenia',
    ioc: 'ARM',
    languages: [
      {
        alpha2: 'hy',
        alpha3: 'hye',
      },
    ],
    numeric: '051',
    shortName: 'Armenia',
  },
  {
    alpha2: 'AO',
    alpha3: 'AGO',
    callingCodes: ['+244'],
    currencies: ['AOA'],
    emoji: '🇦🇴',
    fullName: 'the Republic of Angola',
    ioc: 'ANG',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '024',
    shortName: 'Angola',
    territory: 'Cabinda',
  },
  {
    alpha2: 'AQ',
    alpha3: 'ATA',
    callingCodes: ['+672'],
    emoji: '🇦🇶',
    numeric: '010',
    shortName: 'Antarctica',
  },
  {
    alpha2: 'AR',
    alpha3: 'ARG',
    callingCodes: ['+54'],
    currencies: ['ARS'],
    emoji: '🇦🇷',
    fullName: 'the Argentine Republic',
    ioc: 'ARG',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '032',
    shortName: 'Argentina',
  },
  {
    alpha2: 'AS',
    alpha3: 'ASM',
    callingCodes: ['+1 684'],
    currencies: ['USD'],
    emoji: '🇦🇸',
    ioc: 'ASA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '016',
    shortName: 'American Samoa',
    territory: "Swain's Island, Tutuila",
  },
  {
    alpha2: 'AT',
    alpha3: 'AUT',
    callingCodes: ['+43'],
    currencies: ['EUR'],
    emoji: '🇦🇹',
    fullName: 'the Republic of Austria',
    ioc: 'AUT',
    languages: [
      {
        alpha2: 'de',
        alpha3: 'deu',
      },
    ],
    numeric: '040',
    shortName: 'Austria',
  },
  {
    alpha2: 'AU',
    alpha3: 'AUS',
    callingCodes: ['+61'],
    currencies: ['AUD'],
    emoji: '🇦🇺',
    ioc: 'AUS',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '036',
    shortName: 'Australia',
    territory:
      'Ashmore and Cartier Islands, Coral Sea Islands, Lord Howe Island, Macquarie Island',
  },
  {
    alpha2: 'AW',
    alpha3: 'ABW',
    callingCodes: ['+297'],
    currencies: ['AWG'],
    emoji: '🇦🇼',
    ioc: 'ARU',
    languages: [
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
      {
        alpha2: '',
        alpha3: 'pap',
      },
    ],
    numeric: '533',
    shortName: 'Aruba',
  },
  {
    alpha2: 'AX',
    alpha3: 'ALA',
    callingCodes: ['+358'],
    currencies: ['EUR'],
    emoji: '🇦🇽',
    languages: [
      {
        alpha2: 'sv',
        alpha3: 'swe',
      },
    ],
    numeric: '248',
    shortName: 'Åland Islands',
  },
  {
    alpha2: 'AZ',
    alpha3: 'AZE',
    callingCodes: ['+994'],
    currencies: ['AZN'],
    emoji: '🇦🇿',
    fullName: 'the Republic of Azerbaijan',
    ioc: 'AZE',
    languages: [
      {
        alpha2: 'az',
        alpha3: 'aze',
      },
    ],
    numeric: '031',
    shortName: 'Azerbaijan',
  },
  {
    alpha2: 'BA',
    alpha3: 'BIH',
    callingCodes: ['+387'],
    currencies: ['BAM'],
    emoji: '🇧🇦',
    ioc: 'BIH',
    languages: [
      {
        alpha2: 'bs',
        alpha3: 'bos',
      },
      {
        alpha2: 'hr',
        alpha3: 'hrv',
      },
      {
        alpha2: 'sr',
        alpha3: 'srp',
      },
    ],
    numeric: '070',
    shortName: 'Bosnia and Herzegovina',
    territory: 'Herzegovina',
  },
  {
    alpha2: 'BB',
    alpha3: 'BRB',
    callingCodes: ['+1 246'],
    currencies: ['BBD'],
    emoji: '🇧🇧',
    ioc: 'BAR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '052',
    shortName: 'Barbados',
  },
  {
    alpha2: 'BD',
    alpha3: 'BGD',
    callingCodes: ['+880'],
    currencies: ['BDT'],
    emoji: '🇧🇩',
    fullName: "the People's Republic of Bangladesh",
    ioc: 'BAN',
    languages: [
      {
        alpha2: 'bn',
        alpha3: 'ben',
      },
    ],
    numeric: '050',
    shortName: 'Bangladesh',
  },
  {
    alpha2: 'BE',
    alpha3: 'BEL',
    callingCodes: ['+32'],
    currencies: ['EUR'],
    emoji: '🇧🇪',
    fullName: 'the Kingdom of Belgium',
    ioc: 'BEL',
    languages: [
      {
        alpha2: 'de',
        alpha3: 'deu',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
    ],
    numeric: '056',
    shortName: 'Belgium',
  },
  {
    alpha2: 'BF',
    alpha3: 'BFA',
    callingCodes: ['+226'],
    currencies: ['XOF'],
    emoji: '🇧🇫',
    ioc: 'BUR',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '854',
    shortName: 'Burkina Faso',
  },
  {
    alpha2: 'BG',
    alpha3: 'BGR',
    callingCodes: ['+359'],
    currencies: ['BGN'],
    emoji: '🇧🇬',
    fullName: 'the Republic of Bulgaria',
    ioc: 'BUL',
    languages: [
      {
        alpha2: 'bg',
        alpha3: 'bul',
      },
    ],
    numeric: '100',
    shortName: 'Bulgaria',
  },
  {
    alpha2: 'BH',
    alpha3: 'BHR',
    callingCodes: ['+973'],
    currencies: ['BHD'],
    emoji: '🇧🇭',
    fullName: 'the Kingdom of Bahrain',
    ioc: 'BRN',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '048',
    shortName: 'Bahrain',
  },
  {
    alpha2: 'BI',
    alpha3: 'BDI',
    callingCodes: ['+257'],
    currencies: ['BIF'],
    emoji: '🇧🇮',
    fullName: 'the Republic of Burundi',
    ioc: 'BDI',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'rn',
        alpha3: 'run',
      },
    ],
    numeric: '108',
    shortName: 'Burundi',
  },
  {
    alpha2: 'BJ',
    alpha3: 'BEN',
    callingCodes: ['+229'],
    currencies: ['XOF'],
    emoji: '🇧🇯',
    fullName: 'the Republic of Benin',
    ioc: 'BEN',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '204',
    shortName: 'Benin',
  },
  {
    alpha2: 'BL',
    alpha3: 'BLM',
    callingCodes: ['+590'],
    currencies: ['EUR'],
    emoji: '🇧🇱',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '652',
    shortName: 'Saint Barthélemy',
  },
  {
    alpha2: 'BM',
    alpha3: 'BMU',
    callingCodes: ['+1 441'],
    currencies: ['BMD'],
    emoji: '🇧🇲',
    ioc: 'BER',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '060',
    shortName: 'Bermuda',
  },
  {
    alpha2: 'BN',
    alpha3: 'BRN',
    callingCodes: ['+673'],
    currencies: ['BND'],
    emoji: '🇧🇳',
    ioc: 'BRU',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ms',
        alpha3: 'msa',
      },
    ],
    numeric: '096',
    shortName: 'Brunei Darussalam',
  },
  {
    alpha2: 'BO',
    alpha3: 'BOL',
    callingCodes: ['+591'],
    currencies: ['BOB', 'BOV'],
    emoji: '🇧🇴',
    fullName: 'the Plurinational State of Bolivia',
    ioc: 'BOL',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '068',
    shortName: 'Bolivia (Plurinational State of)',
  },
  {
    alpha2: 'BQ',
    alpha3: 'BES',
    callingCodes: ['+599'],
    currencies: ['USD'],
    emoji: '🇧🇶',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
      {
        alpha2: '',
        alpha3: 'pap',
      },
    ],
    numeric: '535',
    shortName: 'Bonaire, Sint Eustatius and Saba',
    territory: 'Bonaire, Saba, Sint Eustatius',
  },
  {
    alpha2: 'BR',
    alpha3: 'BRA',
    callingCodes: ['+55'],
    currencies: ['BRL'],
    emoji: '🇧🇷',
    fullName: 'the Federative Republic of Brazil',
    ioc: 'BRA',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '076',
    shortName: 'Brazil',
    territory:
      'Fernando de Noronha Island, Martim Vaz Islands, Trindade Island',
  },
  {
    alpha2: 'BS',
    alpha3: 'BHS',
    callingCodes: ['+1 242'],
    currencies: ['BSD'],
    emoji: '🇧🇸',
    fullName: 'the Commonwealth of the Bahamas',
    ioc: 'BAH',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '044',
    shortName: 'Bahamas (the)',
  },
  {
    alpha2: 'BT',
    alpha3: 'BTN',
    callingCodes: ['+975'],
    currencies: ['INR', 'BTN'],
    emoji: '🇧🇹',
    fullName: 'the Kingdom of Bhutan',
    ioc: 'BHU',
    languages: [
      {
        alpha2: 'dz',
        alpha3: 'dzo',
      },
    ],
    numeric: '064',
    shortName: 'Bhutan',
  },
  {
    alpha2: 'BV',
    alpha3: 'BVT',
    currencies: ['NOK'],
    emoji: '🇧🇻',
    languages: [
      {
        alpha2: 'nn',
        alpha3: 'nno',
      },
      {
        alpha2: 'nb',
        alpha3: 'nob',
      },
    ],
    numeric: '074',
    shortName: 'Bouvet Island',
  },
  {
    alpha2: 'BW',
    alpha3: 'BWA',
    callingCodes: ['+267'],
    currencies: ['BWP'],
    emoji: '🇧🇼',
    fullName: 'the Republic of Botswana',
    ioc: 'BOT',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '072',
    shortName: 'Botswana',
  },
  {
    alpha2: 'BY',
    alpha3: 'BLR',
    callingCodes: ['+375'],
    currencies: ['BYN'],
    emoji: '🇧🇾',
    fullName: 'the Republic of Belarus',
    ioc: 'BLR',
    languages: [
      {
        alpha2: 'be',
        alpha3: 'bel',
      },
      {
        alpha2: 'ru',
        alpha3: 'rus',
      },
    ],
    numeric: '112',
    shortName: 'Belarus',
  },
  {
    alpha2: 'BZ',
    alpha3: 'BLZ',
    callingCodes: ['+501'],
    currencies: ['BZD'],
    emoji: '🇧🇿',
    ioc: 'BIZ',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '084',
    shortName: 'Belize',
  },
  {
    alpha2: 'CA',
    alpha3: 'CAN',
    callingCodes: ['+1'],
    currencies: ['CAD'],
    emoji: '🇨🇦',
    ioc: 'CAN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '124',
    shortName: 'Canada',
  },
  {
    alpha2: 'CC',
    alpha3: 'CCK',
    callingCodes: ['+61'],
    currencies: ['AUD'],
    emoji: '🇨🇨',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '166',
    shortName: 'Cocos (Keeling) Islands (the)',
  },
  {
    alpha2: 'CD',
    alpha3: 'COD',
    callingCodes: ['+243'],
    currencies: ['CDF'],
    emoji: '🇨🇩',
    fullName: 'the Democratic Republic of the Congo',
    ioc: 'COD',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '180',
    shortName: 'Congo (the Democratic Republic of the)',
  },
  {
    alpha2: 'CF',
    alpha3: 'CAF',
    callingCodes: ['+236'],
    currencies: ['XAF'],
    emoji: '🇨🇫',
    fullName: 'the Central African Republic',
    ioc: 'CAF',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'sg',
        alpha3: 'sag',
      },
    ],
    numeric: '140',
    shortName: 'Central African Republic (the)',
  },
  {
    alpha2: 'CG',
    alpha3: 'COG',
    callingCodes: ['+242'],
    currencies: ['XAF'],
    emoji: '🇨🇬',
    fullName: 'the Republic of the Congo',
    ioc: 'CGO',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '178',
    shortName: 'Congo (the)',
  },
  {
    alpha2: 'CH',
    alpha3: 'CHE',
    callingCodes: ['+41'],
    currencies: ['CHF', 'CHE', 'CHW'],
    emoji: '🇨🇭',
    fullName: 'the Swiss Confederation',
    ioc: 'SUI',
    languages: [
      {
        alpha2: 'de',
        alpha3: 'deu',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'it',
        alpha3: 'ita',
      },
      {
        alpha2: 'rm',
        alpha3: 'roh',
      },
    ],
    numeric: '756',
    shortName: 'Switzerland',
  },
  {
    alpha2: 'CI',
    alpha3: 'CIV',
    callingCodes: ['+225'],
    currencies: ['XOF'],
    emoji: '🇨🇮',
    fullName: "the Republic of Côte d'Ivoire",
    ioc: 'CIV',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '384',
    shortName: "Côte d'Ivoire",
  },
  {
    alpha2: 'CK',
    alpha3: 'COK',
    callingCodes: ['+682'],
    currencies: ['NZD'],
    emoji: '🇨🇰',
    ioc: 'COK',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '184',
    shortName: 'Cook Islands (the)',
    territory: 'Rarotonga',
  },
  {
    alpha2: 'CL',
    alpha3: 'CHL',
    callingCodes: ['+56'],
    currencies: ['CLP', 'CLF'],
    emoji: '🇨🇱',
    fullName: 'the Republic of Chile',
    ioc: 'CHI',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '152',
    shortName: 'Chile',
    territory:
      'Easter Island, Juan Fernández Islands, Sala y Gómez Island, San Ambrosio Island, San Félix Island',
  },
  {
    alpha2: 'CM',
    alpha3: 'CMR',
    callingCodes: ['+237'],
    currencies: ['XAF'],
    emoji: '🇨🇲',
    fullName: 'the Republic of Cameroon',
    ioc: 'CMR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '120',
    shortName: 'Cameroon',
  },
  {
    alpha2: 'CN',
    alpha3: 'CHN',
    callingCodes: ['+86'],
    currencies: ['CNY'],
    emoji: '🇨🇳',
    fullName: "the People's Republic of China",
    ioc: 'CHN',
    languages: [
      {
        alpha2: 'zh',
        alpha3: 'zho',
      },
    ],
    numeric: '156',
    shortName: 'China',
  },
  {
    alpha2: 'CO',
    alpha3: 'COL',
    callingCodes: ['+57'],
    currencies: ['COP', 'COU'],
    emoji: '🇨🇴',
    fullName: 'the Republic of Colombia',
    ioc: 'COL',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '170',
    shortName: 'Colombia',
    territory: 'Malpelo Island, San Andrés y Providencia Islands',
  },
  {
    alpha2: 'CR',
    alpha3: 'CRI',
    callingCodes: ['+506'],
    currencies: ['CRC'],
    emoji: '🇨🇷',
    fullName: 'the Republic of Costa Rica',
    ioc: 'CRC',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '188',
    shortName: 'Costa Rica',
    territory: 'Coco Island',
  },
  {
    alpha2: 'CU',
    alpha3: 'CUB',
    callingCodes: ['+53'],
    currencies: ['CUP', 'CUC'],
    emoji: '🇨🇺',
    fullName: 'the Republic of Cuba',
    ioc: 'CUB',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '192',
    shortName: 'Cuba',
  },
  {
    alpha2: 'CV',
    alpha3: 'CPV',
    callingCodes: ['+238'],
    currencies: ['CVE'],
    emoji: '🇨🇻',
    fullName: 'the Republic of Cabo Verde',
    ioc: 'CPV',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '132',
    shortName: 'Cabo Verde',
    territory: 'São Tiago, São Vicente',
  },
  {
    alpha2: 'CW',
    alpha3: 'CUW',
    callingCodes: ['+599'],
    currencies: ['ANG'],
    emoji: '🇨🇼',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
      {
        alpha2: '',
        alpha3: 'pap',
      },
    ],
    numeric: '531',
    shortName: 'Curaçao',
  },
  {
    alpha2: 'CX',
    alpha3: 'CXR',
    callingCodes: ['+61'],
    currencies: ['AUD'],
    emoji: '🇨🇽',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '162',
    shortName: 'Christmas Island',
  },
  {
    alpha2: 'CY',
    alpha3: 'CYP',
    callingCodes: ['+357'],
    currencies: ['EUR'],
    emoji: '🇨🇾',
    fullName: 'the Republic of Cyprus',
    ioc: 'CYP',
    languages: [
      {
        alpha2: 'el',
        alpha3: 'ell',
      },
      {
        alpha2: 'tr',
        alpha3: 'tur',
      },
    ],
    numeric: '196',
    shortName: 'Cyprus',
  },
  {
    alpha2: 'CZ',
    alpha3: 'CZE',
    callingCodes: ['+420'],
    currencies: ['CZK'],
    emoji: '🇨🇿',
    fullName: 'the Czech Republic',
    ioc: 'CZE',
    languages: [
      {
        alpha2: 'cs',
        alpha3: 'ces',
      },
    ],
    numeric: '203',
    shortName: 'Czechia',
  },
  {
    alpha2: 'DE',
    alpha3: 'DEU',
    callingCodes: ['+49'],
    currencies: ['EUR'],
    emoji: '🇩🇪',
    fullName: 'the Federal Republic of Germany',
    ioc: 'GER',
    languages: [
      {
        alpha2: 'de',
        alpha3: 'deu',
      },
    ],
    numeric: '276',
    shortName: 'Germany',
  },
  {
    alpha2: 'DJ',
    alpha3: 'DJI',
    callingCodes: ['+253'],
    currencies: ['DJF'],
    emoji: '🇩🇯',
    fullName: 'the Republic of Djibouti',
    ioc: 'DJI',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '262',
    shortName: 'Djibouti',
  },
  {
    alpha2: 'DK',
    alpha3: 'DNK',
    callingCodes: ['+45'],
    currencies: ['DKK'],
    emoji: '🇩🇰',
    fullName: 'the Kingdom of Denmark',
    ioc: 'DEN',
    languages: [
      {
        alpha2: 'da',
        alpha3: 'dan',
      },
    ],
    numeric: '208',
    shortName: 'Denmark',
  },
  {
    alpha2: 'DM',
    alpha3: 'DMA',
    callingCodes: ['+1 767'],
    currencies: ['XCD'],
    emoji: '🇩🇲',
    fullName: 'the Commonwealth of Dominica',
    ioc: 'DMA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '212',
    shortName: 'Dominica',
  },
  {
    alpha2: 'DO',
    alpha3: 'DOM',
    callingCodes: ['+1 809', '+1 829', '+1 849'],
    currencies: ['DOP'],
    emoji: '🇩🇴',
    fullName: 'the Dominican Republic',
    ioc: 'DOM',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '214',
    shortName: 'Dominican Republic (the)',
  },
  {
    alpha2: 'DZ',
    alpha3: 'DZA',
    callingCodes: ['+213'],
    currencies: ['DZD'],
    emoji: '🇩🇿',
    fullName: "the People's Democratic Republic of Algeria",
    ioc: 'ALG',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '012',
    shortName: 'Algeria',
  },
  {
    alpha2: 'EC',
    alpha3: 'ECU',
    callingCodes: ['+593'],
    currencies: ['USD'],
    emoji: '🇪🇨',
    fullName: 'the Republic of Ecuador',
    ioc: 'ECU',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '218',
    shortName: 'Ecuador',
    territory: 'Galápagos Islands',
  },
  {
    alpha2: 'EE',
    alpha3: 'EST',
    callingCodes: ['+372'],
    currencies: ['EUR'],
    emoji: '🇪🇪',
    fullName: 'the Republic of Estonia',
    ioc: 'EST',
    languages: [
      {
        alpha2: 'et',
        alpha3: 'est',
      },
    ],
    numeric: '233',
    shortName: 'Estonia',
  },
  {
    alpha2: 'EG',
    alpha3: 'EGY',
    callingCodes: ['+20'],
    currencies: ['EGP'],
    emoji: '🇪🇬',
    fullName: 'the Arab Republic of Egypt',
    ioc: 'EGY',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '818',
    shortName: 'Egypt',
  },
  {
    alpha2: 'EH',
    alpha3: 'ESH',
    callingCodes: ['+212'],
    currencies: ['MAD'],
    emoji: '🇪🇭',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '732',
    shortName: 'Western Sahara',
  },
  {
    alpha2: 'ER',
    alpha3: 'ERI',
    callingCodes: ['+291'],
    currencies: ['ERN'],
    emoji: '🇪🇷',
    fullName: 'the State of Eritrea',
    ioc: 'ERI',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ti',
        alpha3: 'tir',
      },
    ],
    numeric: '232',
    shortName: 'Eritrea',
  },
  {
    alpha2: 'ES',
    alpha3: 'ESP',
    callingCodes: ['+34'],
    currencies: ['EUR'],
    emoji: '🇪🇸',
    fullName: 'the Kingdom of Spain',
    ioc: 'ESP',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '724',
    shortName: 'Spain',
  },
  {
    alpha2: 'ET',
    alpha3: 'ETH',
    callingCodes: ['+251'],
    currencies: ['ETB'],
    emoji: '🇪🇹',
    fullName: 'the Federal Democratic Republic of Ethiopia',
    ioc: 'ETH',
    languages: [
      {
        alpha2: 'am',
        alpha3: 'amh',
      },
    ],
    numeric: '231',
    shortName: 'Ethiopia',
  },
  {
    alpha2: 'FI',
    alpha3: 'FIN',
    callingCodes: ['+358'],
    currencies: ['EUR'],
    emoji: '🇫🇮',
    fullName: 'the Republic of Finland',
    ioc: 'FIN',
    languages: [
      {
        alpha2: 'fi',
        alpha3: 'fin',
      },
      {
        alpha2: 'sv',
        alpha3: 'swe',
      },
    ],
    numeric: '246',
    shortName: 'Finland',
    territory: 'Åland Islands',
  },
  {
    alpha2: 'FJ',
    alpha3: 'FJI',
    callingCodes: ['+679'],
    currencies: ['FJD'],
    emoji: '🇫🇯',
    fullName: 'the Republic of Fiji',
    ioc: 'FIJ',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fj',
        alpha3: 'fij',
      },
    ],
    numeric: '242',
    shortName: 'Fiji',
    territory: 'Rotuma Island, Vanua Levu, Viti Levu',
  },
  {
    alpha2: 'FK',
    alpha3: 'FLK',
    callingCodes: ['+500'],
    currencies: ['FKP'],
    emoji: '🇫🇰',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '238',
    shortName: 'Falkland Islands (the) [Malvinas]',
  },
  {
    alpha2: 'FM',
    alpha3: 'FSM',
    callingCodes: ['+691'],
    currencies: ['USD'],
    emoji: '🇫🇲',
    fullName: 'the Federated States of Micronesia',
    ioc: 'FSM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '583',
    shortName: 'Micronesia (Federated States of)',
    territory: 'Caroline Islands, Chuuk, Kosrae, Pohnpei, Yap',
  },
  {
    alpha2: 'FO',
    alpha3: 'FRO',
    callingCodes: ['+298'],
    currencies: ['DKK'],
    emoji: '🇫🇴',
    ioc: 'FAI',
    languages: [
      {
        alpha2: 'da',
        alpha3: 'dan',
      },
      {
        alpha2: 'fo',
        alpha3: 'fao',
      },
    ],
    numeric: '234',
    shortName: 'Faroe Islands (the)',
  },
  {
    alpha2: 'FR',
    alpha3: 'FRA',
    callingCodes: ['+33'],
    currencies: ['EUR'],
    emoji: '🇫🇷',
    fullName: 'the French Republic',
    ioc: 'FRA',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '250',
    shortName: 'France',
  },
  {
    alpha2: 'GA',
    alpha3: 'GAB',
    callingCodes: ['+241'],
    currencies: ['XAF'],
    emoji: '🇬🇦',
    fullName: 'the Gabonese Republic',
    ioc: 'GAB',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '266',
    shortName: 'Gabon',
  },
  {
    alpha2: 'GB',
    alpha3: 'GBR',
    callingCodes: ['+44'],
    currencies: ['GBP'],
    emoji: '🇬🇧',
    fullName: 'the United Kingdom of Great Britain and Northern Ireland',
    ioc: 'GBR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '826',
    shortName: 'United Kingdom of Great Britain and Northern Ireland (the)',
  },
  {
    alpha2: 'GD',
    alpha3: 'GRD',
    callingCodes: ['+473'],
    currencies: ['XCD'],
    emoji: '🇬🇩',
    ioc: 'GRN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '308',
    shortName: 'Grenada',
    territory: 'Carriacou, Southern Grenadine Islands',
  },
  {
    alpha2: 'GE',
    alpha3: 'GEO',
    callingCodes: ['+995'],
    currencies: ['GEL'],
    emoji: '🇬🇪',
    ioc: 'GEO',
    languages: [
      {
        alpha2: 'ka',
        alpha3: 'kat',
      },
    ],
    numeric: '268',
    shortName: 'Georgia',
  },
  {
    alpha2: 'GF',
    alpha3: 'GUF',
    callingCodes: ['+594'],
    currencies: ['EUR'],
    emoji: '🇬🇫',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '254',
    shortName: 'French Guiana',
  },
  {
    alpha2: 'GG',
    alpha3: 'GGY',
    callingCodes: ['+44'],
    currencies: ['GBP'],
    emoji: '🇬🇬',
    ioc: 'GCI',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '831',
    shortName: 'Guernsey',
    territory:
      'Alderney Island, Brecqhou Island, Burhou Island, Sark Island, Herm Island, Jethou Island, Lihou Island, Little Sark Island',
  },
  {
    alpha2: 'GH',
    alpha3: 'GHA',
    callingCodes: ['+233'],
    currencies: ['GHS'],
    emoji: '🇬🇭',
    fullName: 'the Republic of Ghana',
    ioc: 'GHA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '288',
    shortName: 'Ghana',
  },
  {
    alpha2: 'GI',
    alpha3: 'GIB',
    callingCodes: ['+350'],
    currencies: ['GIP'],
    emoji: '🇬🇮',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '292',
    shortName: 'Gibraltar',
  },
  {
    alpha2: 'GL',
    alpha3: 'GRL',
    callingCodes: ['+299'],
    currencies: ['DKK'],
    emoji: '🇬🇱',
    languages: [
      {
        alpha2: 'da',
        alpha3: 'dan',
      },
      {
        alpha2: 'kl',
        alpha3: 'kal',
      },
    ],
    numeric: '304',
    shortName: 'Greenland',
  },
  {
    alpha2: 'GM',
    alpha3: 'GMB',
    callingCodes: ['+220'],
    currencies: ['GMD'],
    emoji: '🇬🇲',
    fullName: 'the Republic of the Gambia',
    ioc: 'GAM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '270',
    shortName: 'Gambia (the)',
  },
  {
    alpha2: 'GN',
    alpha3: 'GIN',
    callingCodes: ['+224'],
    currencies: ['GNF'],
    emoji: '🇬🇳',
    fullName: 'the Republic of Guinea',
    ioc: 'GUI',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '324',
    shortName: 'Guinea',
  },
  {
    alpha2: 'GP',
    alpha3: 'GLP',
    callingCodes: ['+590'],
    currencies: ['EUR'],
    emoji: '🇬🇵',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '312',
    shortName: 'Guadeloupe',
    territory: 'la Désirade, Marie-Galante, les Saintes',
  },
  {
    alpha2: 'GQ',
    alpha3: 'GNQ',
    callingCodes: ['+240'],
    currencies: ['XAF'],
    emoji: '🇬🇶',
    fullName: 'the Republic of Equatorial Guinea',
    ioc: 'GEQ',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '226',
    shortName: 'Equatorial Guinea',
    territory:
      'Annobón Island, Bioko Island, Continental Region (Rio Muni), Rio Muni',
  },
  {
    alpha2: 'GR',
    alpha3: 'GRC',
    callingCodes: ['+30'],
    currencies: ['EUR'],
    emoji: '🇬🇷',
    fullName: 'the Hellenic Republic',
    ioc: 'GRE',
    languages: [
      {
        alpha2: 'el',
        alpha3: 'ell',
      },
    ],
    numeric: '300',
    shortName: 'Greece',
    territory: 'Mount Athos autonomous area',
  },
  {
    alpha2: 'GS',
    alpha3: 'SGS',
    currencies: ['GBP'],
    emoji: '🇬🇸',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '239',
    shortName: 'South Georgia and the South Sandwich Islands',
    territory: 'South Sandwich Islands',
  },
  {
    alpha2: 'GT',
    alpha3: 'GTM',
    callingCodes: ['+502'],
    currencies: ['GTQ'],
    emoji: '🇬🇹',
    fullName: 'the Republic of Guatemala',
    ioc: 'GUA',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '320',
    shortName: 'Guatemala',
  },
  {
    alpha2: 'GU',
    alpha3: 'GUM',
    callingCodes: ['+1 671'],
    currencies: ['USD'],
    emoji: '🇬🇺',
    ioc: 'GUM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '316',
    shortName: 'Guam',
  },
  {
    alpha2: 'GW',
    alpha3: 'GNB',
    callingCodes: ['+245'],
    currencies: ['XOF'],
    emoji: '🇬🇼',
    fullName: 'the Republic of Guinea-Bissau',
    ioc: 'GBS',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '624',
    shortName: 'Guinea-Bissau',
  },
  {
    alpha2: 'GY',
    alpha3: 'GUY',
    callingCodes: ['+592'],
    currencies: ['GYD'],
    emoji: '🇬🇾',
    fullName: 'the Co-operative Republic of Guyana',
    ioc: 'GUY',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '328',
    shortName: 'Guyana',
  },
  {
    alpha2: 'HK',
    alpha3: 'HKG',
    callingCodes: ['+852'],
    currencies: ['HKD'],
    emoji: '🇭🇰',
    fullName: 'the Hong Kong Special Administrative Region of China',
    ioc: 'HKG',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'zh',
        alpha3: 'zho',
      },
    ],
    numeric: '344',
    shortName: 'Hong Kong',
  },
  {
    alpha2: 'HM',
    alpha3: 'HMD',
    currencies: ['AUD'],
    emoji: '🇭🇲',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '334',
    shortName: 'Heard Island and McDonald Islands',
    territory: 'McDonald Islands',
  },
  {
    alpha2: 'HN',
    alpha3: 'HND',
    callingCodes: ['+504'],
    currencies: ['HNL'],
    emoji: '🇭🇳',
    fullName: 'the Republic of Honduras',
    ioc: 'HON',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '340',
    shortName: 'Honduras',
    territory: 'Swan Islands',
  },
  {
    alpha2: 'HR',
    alpha3: 'HRV',
    callingCodes: ['+385'],
    currencies: ['HRK'],
    emoji: '🇭🇷',
    fullName: 'the Republic of Croatia',
    ioc: 'CRO',
    languages: [
      {
        alpha2: 'hr',
        alpha3: 'hrv',
      },
    ],
    numeric: '191',
    shortName: 'Croatia',
  },
  {
    alpha2: 'HT',
    alpha3: 'HTI',
    callingCodes: ['+509'],
    currencies: ['HTG', 'USD'],
    emoji: '🇭🇹',
    fullName: 'the Republic of Haiti',
    ioc: 'HAI',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'ht',
        alpha3: 'hat',
      },
    ],
    numeric: '332',
    shortName: 'Haiti',
  },
  {
    alpha2: 'HU',
    alpha3: 'HUN',
    callingCodes: ['+36'],
    currencies: ['HUF'],
    emoji: '🇭🇺',
    ioc: 'HUN',
    languages: [
      {
        alpha2: 'hu',
        alpha3: 'hun',
      },
    ],
    numeric: '348',
    shortName: 'Hungary',
  },
  {
    alpha2: 'ID',
    alpha3: 'IDN',
    callingCodes: ['+62'],
    currencies: ['IDR'],
    emoji: '🇮🇩',
    fullName: 'the Republic of Indonesia',
    ioc: 'INA',
    languages: [
      {
        alpha2: 'id',
        alpha3: 'ind',
      },
    ],
    numeric: '360',
    shortName: 'Indonesia',
  },
  {
    alpha2: 'IE',
    alpha3: 'IRL',
    callingCodes: ['+353'],
    currencies: ['EUR'],
    emoji: '🇮🇪',
    ioc: 'IRL',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ga',
        alpha3: 'gle',
      },
    ],
    numeric: '372',
    shortName: 'Ireland',
  },
  {
    alpha2: 'IL',
    alpha3: 'ISR',
    callingCodes: ['+972'],
    currencies: ['ILS'],
    emoji: '🇮🇱',
    fullName: 'the State of Israel',
    ioc: 'ISR',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'he',
        alpha3: 'heb',
      },
    ],
    numeric: '376',
    shortName: 'Israel',
  },
  {
    alpha2: 'IM',
    alpha3: 'IMN',
    callingCodes: ['+44'],
    currencies: ['GBP'],
    emoji: '🇮🇲',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '833',
    shortName: 'Isle of Man',
  },
  {
    alpha2: 'IN',
    alpha3: 'IND',
    callingCodes: ['+91'],
    currencies: ['INR'],
    emoji: '🇮🇳',
    fullName: 'the Republic of India',
    ioc: 'IND',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'hi',
        alpha3: 'hin',
      },
    ],
    numeric: '356',
    shortName: 'India',
    territory:
      'Andaman Islands, Laccadive Islands, Minicoy Island, Nicobar Islands, Amindivi Islands',
  },
  {
    alpha2: 'IO',
    alpha3: 'IOT',
    callingCodes: ['+246'],
    currencies: ['USD'],
    emoji: '🇮🇴',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '086',
    shortName: 'British Indian Ocean Territory (the)',
    territory: 'Chagos Archipelago, Diego Garcia',
  },
  {
    alpha2: 'IQ',
    alpha3: 'IRQ',
    callingCodes: ['+964'],
    currencies: ['IQD'],
    emoji: '🇮🇶',
    fullName: 'the Republic of Iraq',
    ioc: 'IRQ',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'ku',
        alpha3: 'kur',
      },
    ],
    numeric: '368',
    shortName: 'Iraq',
  },
  {
    alpha2: 'IR',
    alpha3: 'IRN',
    callingCodes: ['+98'],
    currencies: ['IRR'],
    emoji: '🇮🇷',
    fullName: 'the Islamic Republic of Iran',
    ioc: 'IRI',
    languages: [
      {
        alpha2: 'fa',
        alpha3: 'fas',
      },
    ],
    numeric: '364',
    shortName: 'Iran (Islamic Republic of)',
  },
  {
    alpha2: 'IS',
    alpha3: 'ISL',
    callingCodes: ['+354'],
    currencies: ['ISK'],
    emoji: '🇮🇸',
    fullName: 'the Republic of Iceland',
    ioc: 'ISL',
    languages: [
      {
        alpha2: 'is',
        alpha3: 'isl',
      },
    ],
    numeric: '352',
    shortName: 'Iceland',
  },
  {
    alpha2: 'IT',
    alpha3: 'ITA',
    callingCodes: ['+39'],
    currencies: ['EUR'],
    emoji: '🇮🇹',
    fullName: 'the Republic of Italy',
    ioc: 'ITA',
    languages: [
      {
        alpha2: 'it',
        alpha3: 'ita',
      },
    ],
    numeric: '380',
    shortName: 'Italy',
  },
  {
    alpha2: 'JE',
    alpha3: 'JEY',
    callingCodes: ['+44'],
    currencies: ['GBP'],
    emoji: '🇯🇪',
    ioc: 'JCI',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '832',
    shortName: 'Jersey',
  },
  {
    alpha2: 'JM',
    alpha3: 'JAM',
    callingCodes: ['+1 876'],
    currencies: ['JMD'],
    emoji: '🇯🇲',
    ioc: 'JAM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '388',
    shortName: 'Jamaica',
  },
  {
    alpha2: 'JO',
    alpha3: 'JOR',
    callingCodes: ['+962'],
    currencies: ['JOD'],
    emoji: '🇯🇴',
    fullName: 'the Hashemite Kingdom of Jordan',
    ioc: 'JOR',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '400',
    shortName: 'Jordan',
  },
  {
    alpha2: 'JP',
    alpha3: 'JPN',
    callingCodes: ['+81'],
    currencies: ['JPY'],
    emoji: '🇯🇵',
    ioc: 'JPN',
    languages: [
      {
        alpha2: 'ja',
        alpha3: 'jpn',
      },
    ],
    numeric: '392',
    shortName: 'Japan',
  },
  {
    alpha2: 'KE',
    alpha3: 'KEN',
    callingCodes: ['+254'],
    currencies: ['KES'],
    emoji: '🇰🇪',
    fullName: 'the Republic of Kenya',
    ioc: 'KEN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'sw',
        alpha3: 'swa',
      },
    ],
    numeric: '404',
    shortName: 'Kenya',
  },
  {
    alpha2: 'KG',
    alpha3: 'KGZ',
    callingCodes: ['+996'],
    currencies: ['KGS'],
    emoji: '🇰🇬',
    fullName: 'the Kyrgyz Republic',
    ioc: 'KGZ',
    languages: [
      {
        alpha2: 'ky',
        alpha3: 'kir',
      },
      {
        alpha2: 'ru',
        alpha3: 'rus',
      },
    ],
    numeric: '417',
    shortName: 'Kyrgyzstan',
  },
  {
    alpha2: 'KH',
    alpha3: 'KHM',
    callingCodes: ['+855'],
    currencies: ['KHR'],
    emoji: '🇰🇭',
    fullName: 'the Kingdom of Cambodia',
    ioc: 'CAM',
    languages: [
      {
        alpha2: 'km',
        alpha3: 'khm',
      },
    ],
    numeric: '116',
    shortName: 'Cambodia',
  },
  {
    alpha2: 'KI',
    alpha3: 'KIR',
    callingCodes: ['+686'],
    currencies: ['AUD'],
    emoji: '🇰🇮',
    fullName: 'the Republic of Kiribati',
    ioc: 'KIR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: '',
        alpha3: 'gil',
      },
    ],
    numeric: '296',
    shortName: 'Kiribati',
    territory:
      'Abariringa, Banaba, Enderbury Island, Gilbert Islands, Kiritimati, part of Line Islands, Phoenix Islands, Tarawa',
  },
  {
    alpha2: 'KM',
    alpha3: 'COM',
    callingCodes: ['+269'],
    currencies: ['KMF'],
    emoji: '🇰🇲',
    fullName: 'the Union of the Comoros',
    ioc: 'COM',
    languages: [
      {
        alpha2: '',
        alpha3: '002',
      },
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '174',
    shortName: 'Comoros (the)',
    territory: 'Anjouan, Grande Comore, Mohéli',
  },
  {
    alpha2: 'KN',
    alpha3: 'KNA',
    callingCodes: ['+1 869'],
    currencies: ['XCD'],
    emoji: '🇰🇳',
    ioc: 'SKN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '659',
    shortName: 'Saint Kitts and Nevis',
    territory: 'Nevis',
  },
  {
    alpha2: 'KP',
    alpha3: 'PRK',
    callingCodes: ['+850'],
    currencies: ['KPW'],
    emoji: '🇰🇵',
    fullName: "the Democratic People's Republic of Korea",
    ioc: 'PRK',
    languages: [
      {
        alpha2: 'ko',
        alpha3: 'kor',
      },
    ],
    numeric: '408',
    shortName: "Korea (the Democratic People's Republic of)",
  },
  {
    alpha2: 'KR',
    alpha3: 'KOR',
    callingCodes: ['+82'],
    currencies: ['KRW'],
    emoji: '🇰🇷',
    fullName: 'the Republic of Korea',
    ioc: 'KOR',
    languages: [
      {
        alpha2: 'ko',
        alpha3: 'kor',
      },
    ],
    numeric: '410',
    shortName: 'Korea (the Republic of)',
  },
  {
    alpha2: 'KW',
    alpha3: 'KWT',
    callingCodes: ['+965'],
    currencies: ['KWD'],
    emoji: '🇰🇼',
    fullName: 'the State of Kuwait',
    ioc: 'KUW',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '414',
    shortName: 'Kuwait',
  },
  {
    alpha2: 'KY',
    alpha3: 'CYM',
    callingCodes: ['+1 345'],
    currencies: ['KYD'],
    emoji: '🇰🇾',
    ioc: 'CAY',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '136',
    shortName: 'Cayman Islands (the)',
    territory: 'Grand Cayman',
  },
  {
    alpha2: 'KZ',
    alpha3: 'KAZ',
    callingCodes: ['+7', '+7 6', '+7 7'],
    currencies: ['KZT'],
    emoji: '🇰🇿',
    fullName: 'the Republic of Kazakhstan',
    ioc: 'KAZ',
    languages: [
      {
        alpha2: 'kk',
        alpha3: 'kaz',
      },
      {
        alpha2: 'ru',
        alpha3: 'rus',
      },
    ],
    numeric: '398',
    shortName: 'Kazakhstan',
  },
  {
    alpha2: 'LA',
    alpha3: 'LAO',
    callingCodes: ['+856'],
    currencies: ['LAK'],
    emoji: '🇱🇦',
    fullName: "the Lao People's Democratic Republic",
    ioc: 'LAO',
    languages: [
      {
        alpha2: 'lo',
        alpha3: 'lao',
      },
    ],
    numeric: '418',
    shortName: "Lao People's Democratic Republic (the)",
  },
  {
    alpha2: 'LB',
    alpha3: 'LBN',
    callingCodes: ['+961'],
    currencies: ['LBP'],
    emoji: '🇱🇧',
    fullName: 'the Lebanese Republic',
    ioc: 'LIB',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '422',
    shortName: 'Lebanon',
  },
  {
    alpha2: 'LC',
    alpha3: 'LCA',
    callingCodes: ['+1 758'],
    currencies: ['XCD'],
    emoji: '🇱🇨',
    ioc: 'LCA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '662',
    shortName: 'Saint Lucia',
  },
  {
    alpha2: 'LI',
    alpha3: 'LIE',
    callingCodes: ['+423'],
    currencies: ['CHF'],
    emoji: '🇱🇮',
    fullName: 'the Principality of Liechtenstein',
    ioc: 'LIE',
    languages: [
      {
        alpha2: 'de',
        alpha3: 'deu',
      },
    ],
    numeric: '438',
    shortName: 'Liechtenstein',
  },
  {
    alpha2: 'LK',
    alpha3: 'LKA',
    callingCodes: ['+94'],
    currencies: ['LKR'],
    emoji: '🇱🇰',
    fullName: 'the Democratic Socialist Republic of Sri Lanka',
    ioc: 'SRI',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'si',
        alpha3: 'sin',
      },
      {
        alpha2: 'ta',
        alpha3: 'tam',
      },
    ],
    numeric: '144',
    shortName: 'Sri Lanka',
  },
  {
    alpha2: 'LR',
    alpha3: 'LBR',
    callingCodes: ['+231'],
    currencies: ['LRD'],
    emoji: '🇱🇷',
    fullName: 'the Republic of Liberia',
    ioc: 'LBR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '430',
    shortName: 'Liberia',
  },
  {
    alpha2: 'LS',
    alpha3: 'LSO',
    callingCodes: ['+266'],
    currencies: ['LSL', 'ZAR'],
    emoji: '🇱🇸',
    fullName: 'the Kingdom of Lesotho',
    ioc: 'LES',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'st',
        alpha3: 'sot',
      },
    ],
    numeric: '426',
    shortName: 'Lesotho',
  },
  {
    alpha2: 'LT',
    alpha3: 'LTU',
    callingCodes: ['+370'],
    currencies: ['EUR'],
    emoji: '🇱🇹',
    fullName: 'the Republic of Lithuania',
    ioc: 'LTU',
    languages: [
      {
        alpha2: 'lt',
        alpha3: 'lit',
      },
    ],
    numeric: '440',
    shortName: 'Lithuania',
  },
  {
    alpha2: 'LU',
    alpha3: 'LUX',
    callingCodes: ['+352'],
    currencies: ['EUR'],
    emoji: '🇱🇺',
    fullName: 'the Grand Duchy of Luxembourg',
    ioc: 'LUX',
    languages: [
      {
        alpha2: 'de',
        alpha3: 'deu',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'lb',
        alpha3: 'ltz',
      },
    ],
    numeric: '442',
    shortName: 'Luxembourg',
  },
  {
    alpha2: 'LV',
    alpha3: 'LVA',
    callingCodes: ['+371'],
    currencies: ['EUR'],
    emoji: '🇱🇻',
    fullName: 'the Republic of Latvia',
    ioc: 'LAT',
    languages: [
      {
        alpha2: 'lv',
        alpha3: 'lav',
      },
    ],
    numeric: '428',
    shortName: 'Latvia',
  },
  {
    alpha2: 'LY',
    alpha3: 'LBY',
    callingCodes: ['+218'],
    currencies: ['LYD'],
    emoji: '🇱🇾',
    fullName: 'the State of Libya',
    ioc: 'LBA',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '434',
    shortName: 'Libya',
  },
  {
    alpha2: 'MA',
    alpha3: 'MAR',
    callingCodes: ['+212'],
    currencies: ['MAD'],
    emoji: '🇲🇦',
    fullName: 'the Kingdom of Morocco',
    ioc: 'MAR',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '504',
    shortName: 'Morocco',
  },
  {
    alpha2: 'MC',
    alpha3: 'MCO',
    callingCodes: ['+377'],
    currencies: ['EUR'],
    emoji: '🇲🇨',
    fullName: 'the Principality of Monaco',
    ioc: 'MON',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '492',
    shortName: 'Monaco',
  },
  {
    alpha2: 'MD',
    alpha3: 'MDA',
    callingCodes: ['+373'],
    currencies: ['MDL'],
    emoji: '🇲🇩',
    fullName: 'the Republic of Moldova',
    ioc: 'MDA',
    languages: [
      {
        alpha2: 'ro',
        alpha3: 'ron',
      },
    ],
    numeric: '498',
    shortName: 'Moldova (the Republic of)',
  },
  {
    alpha2: 'ME',
    alpha3: 'MNE',
    callingCodes: ['+382'],
    currencies: ['EUR'],
    emoji: '🇲🇪',
    ioc: 'MNE',
    languages: [
      {
        alpha2: '',
        alpha3: 'cnr',
      },
    ],
    numeric: '499',
    shortName: 'Montenegro',
  },
  {
    alpha2: 'MF',
    alpha3: 'MAF',
    callingCodes: ['+590'],
    currencies: ['EUR'],
    emoji: '🇲🇫',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '663',
    shortName: 'Saint Martin (French part)',
  },
  {
    alpha2: 'MG',
    alpha3: 'MDG',
    callingCodes: ['+261'],
    currencies: ['MGA'],
    emoji: '🇲🇬',
    fullName: 'the Republic of Madagascar',
    ioc: 'MAD',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'mg',
        alpha3: 'mlg',
      },
    ],
    numeric: '450',
    shortName: 'Madagascar',
  },
  {
    alpha2: 'MH',
    alpha3: 'MHL',
    callingCodes: ['+692'],
    currencies: ['USD'],
    emoji: '🇲🇭',
    fullName: 'the Republic of the Marshall Islands',
    ioc: 'MHL',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'mh',
        alpha3: 'mah',
      },
    ],
    numeric: '584',
    shortName: 'Marshall Islands (the)',
    territory: 'Jaluit, Kwajalein, Majuro',
  },
  {
    alpha2: 'MK',
    alpha3: 'MKD',
    callingCodes: ['+389'],
    currencies: ['MKD'],
    emoji: '🇲🇰',
    fullName: 'the Republic of North Macedonia',
    ioc: 'MKD',
    languages: [
      {
        alpha2: 'mk',
        alpha3: 'mkd',
      },
    ],
    numeric: '807',
    shortName: 'North Macedonia',
  },
  {
    alpha2: 'ML',
    alpha3: 'MLI',
    callingCodes: ['+223'],
    currencies: ['XOF'],
    emoji: '🇲🇱',
    fullName: 'the Republic of Mali',
    ioc: 'MLI',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '466',
    shortName: 'Mali',
  },
  {
    alpha2: 'MM',
    alpha3: 'MMR',
    callingCodes: ['+95'],
    currencies: ['MMK'],
    emoji: '🇲🇲',
    fullName: 'the Republic of the Union of Myanmar',
    ioc: 'MYA',
    languages: [
      {
        alpha2: 'my',
        alpha3: 'mya',
      },
    ],
    numeric: '104',
    shortName: 'Myanmar',
  },
  {
    alpha2: 'MN',
    alpha3: 'MNG',
    callingCodes: ['+976'],
    currencies: ['MNT'],
    emoji: '🇲🇳',
    ioc: 'MGL',
    languages: [
      {
        alpha2: 'mn',
        alpha3: 'mon',
      },
    ],
    numeric: '496',
    shortName: 'Mongolia',
  },
  {
    alpha2: 'MO',
    alpha3: 'MAC',
    callingCodes: ['+853'],
    currencies: ['MOP'],
    emoji: '🇲🇴',
    fullName: 'Macao Special Administrative Region of China',
    ioc: 'MAC',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
      {
        alpha2: 'zh',
        alpha3: 'zho',
      },
    ],
    numeric: '446',
    shortName: 'Macao',
  },
  {
    alpha2: 'MP',
    alpha3: 'MNP',
    callingCodes: ['+1 670'],
    currencies: ['USD'],
    emoji: '🇲🇵',
    fullName: 'the Commonwealth of the Northern Mariana Islands',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '580',
    shortName: 'Northern Mariana Islands (the)',
    territory: 'Mariana Islands (except GUAM), Saipan (principal island)',
  },
  {
    alpha2: 'MQ',
    alpha3: 'MTQ',
    callingCodes: ['+596'],
    currencies: ['EUR'],
    emoji: '🇲🇶',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '474',
    shortName: 'Martinique',
  },
  {
    alpha2: 'MR',
    alpha3: 'MRT',
    callingCodes: ['+222'],
    currencies: ['MRO'],
    emoji: '🇲🇷',
    fullName: 'the Islamic Republic of Mauritania',
    ioc: 'MTN',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '478',
    shortName: 'Mauritania',
  },
  {
    alpha2: 'MS',
    alpha3: 'MSR',
    callingCodes: ['+1 664'],
    currencies: ['XCD'],
    emoji: '🇲🇸',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '500',
    shortName: 'Montserrat',
  },
  {
    alpha2: 'MT',
    alpha3: 'MLT',
    callingCodes: ['+356'],
    currencies: ['EUR'],
    emoji: '🇲🇹',
    fullName: 'the Republic of Malta',
    ioc: 'MLT',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'mt',
        alpha3: 'mlt',
      },
    ],
    numeric: '470',
    shortName: 'Malta',
  },
  {
    alpha2: 'MU',
    alpha3: 'MUS',
    callingCodes: ['+230'],
    currencies: ['MUR'],
    emoji: '🇲🇺',
    fullName: 'the Republic of Mauritius',
    ioc: 'MRI',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '480',
    shortName: 'Mauritius',
    territory: 'Agalega Islands, Cargados Carajos Shoals, Rodrigues Island',
  },
  {
    alpha2: 'MV',
    alpha3: 'MDV',
    callingCodes: ['+960'],
    currencies: ['MVR'],
    emoji: '🇲🇻',
    fullName: 'the Republic of Maldives',
    ioc: 'MDV',
    languages: [
      {
        alpha2: 'dv',
        alpha3: 'div',
      },
    ],
    numeric: '462',
    shortName: 'Maldives',
  },
  {
    alpha2: 'MW',
    alpha3: 'MWI',
    callingCodes: ['+265'],
    currencies: ['MWK'],
    emoji: '🇲🇼',
    fullName: 'the Republic of Malawi',
    ioc: 'MAW',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ny',
        alpha3: 'nya',
      },
    ],
    numeric: '454',
    shortName: 'Malawi',
  },
  {
    alpha2: 'MX',
    alpha3: 'MEX',
    callingCodes: ['+52'],
    currencies: ['MXN', 'MXV'],
    emoji: '🇲🇽',
    fullName: 'the United Mexican States',
    ioc: 'MEX',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '484',
    shortName: 'Mexico',
  },
  {
    alpha2: 'MY',
    alpha3: 'MYS',
    callingCodes: ['+60'],
    currencies: ['MYR'],
    emoji: '🇲🇾',
    ioc: 'MAS',
    languages: [
      {
        alpha2: 'ms',
        alpha3: 'msa',
      },
    ],
    numeric: '458',
    shortName: 'Malaysia',
    territory: 'Peninsular Malaysia, Sabah, Sarawak',
  },
  {
    alpha2: 'MZ',
    alpha3: 'MOZ',
    callingCodes: ['+258'],
    currencies: ['MZN'],
    emoji: '🇲🇿',
    fullName: 'the Republic of Mozambique',
    ioc: 'MOZ',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '508',
    shortName: 'Mozambique',
  },
  {
    alpha2: 'NA',
    alpha3: 'NAM',
    callingCodes: ['+264'],
    currencies: ['NAD', 'ZAR'],
    emoji: '🇳🇦',
    fullName: 'the Republic of Namibia',
    ioc: 'NAM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '516',
    shortName: 'Namibia',
  },
  {
    alpha2: 'NC',
    alpha3: 'NCL',
    callingCodes: ['+687'],
    currencies: ['XPF'],
    emoji: '🇳🇨',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '540',
    shortName: 'New Caledonia',
    territory: 'Loyalty Islands',
  },
  {
    alpha2: 'NE',
    alpha3: 'NER',
    callingCodes: ['+227'],
    currencies: ['XOF'],
    emoji: '🇳🇪',
    fullName: 'the Republic of the Niger',
    ioc: 'NIG',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '562',
    shortName: 'Niger (the)',
  },
  {
    alpha2: 'NF',
    alpha3: 'NFK',
    callingCodes: ['+672'],
    currencies: ['AUD'],
    emoji: '🇳🇫',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '574',
    shortName: 'Norfolk Island',
  },
  {
    alpha2: 'NG',
    alpha3: 'NGA',
    callingCodes: ['+234'],
    currencies: ['NGN'],
    emoji: '🇳🇬',
    fullName: 'the Federal Republic of Nigeria',
    ioc: 'NGR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '566',
    shortName: 'Nigeria',
  },
  {
    alpha2: 'NI',
    alpha3: 'NIC',
    callingCodes: ['+505'],
    currencies: ['NIO'],
    emoji: '🇳🇮',
    fullName: 'the Republic of Nicaragua',
    ioc: 'NCA',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '558',
    shortName: 'Nicaragua',
  },
  {
    alpha2: 'NL',
    alpha3: 'NLD',
    callingCodes: ['+31'],
    currencies: ['EUR'],
    emoji: '🇳🇱',
    fullName: 'the Kingdom of the Netherlands',
    ioc: 'NED',
    languages: [
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
    ],
    numeric: '528',
    shortName: 'Netherlands (the)',
  },
  {
    alpha2: 'NO',
    alpha3: 'NOR',
    callingCodes: ['+47'],
    currencies: ['NOK'],
    emoji: '🇳🇴',
    fullName: 'the Kingdom of Norway',
    ioc: 'NOR',
    languages: [
      {
        alpha2: 'nn',
        alpha3: 'nno',
      },
      {
        alpha2: 'nb',
        alpha3: 'nob',
      },
    ],
    numeric: '578',
    shortName: 'Norway',
  },
  {
    alpha2: 'NP',
    alpha3: 'NPL',
    callingCodes: ['+977'],
    currencies: ['NPR'],
    emoji: '🇳🇵',
    fullName: 'the Federal Democratic Republic of Nepal',
    ioc: 'NEP',
    languages: [
      {
        alpha2: 'ne',
        alpha3: 'nep',
      },
    ],
    numeric: '524',
    shortName: 'Nepal',
  },
  {
    alpha2: 'NR',
    alpha3: 'NRU',
    callingCodes: ['+674'],
    currencies: ['AUD'],
    emoji: '🇳🇷',
    fullName: 'the Republic of Nauru',
    ioc: 'NRU',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'na',
        alpha3: 'nau',
      },
    ],
    numeric: '520',
    shortName: 'Nauru',
  },
  {
    alpha2: 'NU',
    alpha3: 'NIU',
    callingCodes: ['+683'],
    currencies: ['NZD'],
    emoji: '🇳🇺',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: '',
        alpha3: 'niu',
      },
    ],
    numeric: '570',
    shortName: 'Niue',
  },
  {
    alpha2: 'NZ',
    alpha3: 'NZL',
    callingCodes: ['+64'],
    currencies: ['NZD'],
    emoji: '🇳🇿',
    ioc: 'NZL',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'mi',
        alpha3: 'mri',
      },
    ],
    numeric: '554',
    shortName: 'New Zealand',
    territory:
      'Antipodes Islands, Auckland Islands, Campbell Island, Chatham Islands, Kermadec Islands',
  },
  {
    alpha2: 'OM',
    alpha3: 'OMN',
    callingCodes: ['+968'],
    currencies: ['OMR'],
    emoji: '🇴🇲',
    fullName: 'the Sultanate of Oman',
    ioc: 'OMA',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '512',
    shortName: 'Oman',
    territory: 'part of the Musandam Peninsula',
  },
  {
    alpha2: 'PA',
    alpha3: 'PAN',
    callingCodes: ['+507'],
    currencies: ['PAB', 'USD'],
    emoji: '🇵🇦',
    fullName: 'the Republic of Panama',
    ioc: 'PAN',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '591',
    shortName: 'Panama',
  },
  {
    alpha2: 'PE',
    alpha3: 'PER',
    callingCodes: ['+51'],
    currencies: ['PEN'],
    emoji: '🇵🇪',
    fullName: 'the Republic of Peru',
    ioc: 'PER',
    languages: [
      {
        alpha2: 'ay',
        alpha3: 'aym',
      },
      {
        alpha2: 'qu',
        alpha3: 'que',
      },
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '604',
    shortName: 'Peru',
  },
  {
    alpha2: 'PF',
    alpha3: 'PYF',
    callingCodes: ['+689'],
    currencies: ['XPF'],
    emoji: '🇵🇫',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '258',
    shortName: 'French Polynesia',
    territory:
      'Austral Islands, Gambier Islands, Marquesas Islands, Society Archipelago, Tahiti, Tuamotu Islands',
  },
  {
    alpha2: 'PG',
    alpha3: 'PNG',
    callingCodes: ['+675'],
    currencies: ['PGK'],
    emoji: '🇵🇬',
    fullName: 'the Independent State of Papua New Guinea',
    ioc: 'PNG',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ho',
        alpha3: 'hmo',
      },
      {
        alpha2: '',
        alpha3: 'tpi',
      },
    ],
    numeric: '598',
    shortName: 'Papua New Guinea',
    territory:
      'Bismarck Archipelago, Bougainville (principal island), Solomon Islands, Northern',
  },
  {
    alpha2: 'PH',
    alpha3: 'PHL',
    callingCodes: ['+63'],
    currencies: ['PHP'],
    emoji: '🇵🇭',
    fullName: 'the Republic of the Philippines',
    ioc: 'PHI',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'tl',
        alpha3: 'tgl',
      },
    ],
    numeric: '608',
    shortName: 'Philippines (the)',
  },
  {
    alpha2: 'PK',
    alpha3: 'PAK',
    callingCodes: ['+92'],
    currencies: ['PKR'],
    emoji: '🇵🇰',
    fullName: 'the Islamic Republic of Pakistan',
    ioc: 'PAK',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ur',
        alpha3: 'urd',
      },
    ],
    numeric: '586',
    shortName: 'Pakistan',
  },
  {
    alpha2: 'PL',
    alpha3: 'POL',
    callingCodes: ['+48'],
    currencies: ['PLN'],
    emoji: '🇵🇱',
    fullName: 'the Republic of Poland',
    ioc: 'POL',
    languages: [
      {
        alpha2: 'pl',
        alpha3: 'pol',
      },
    ],
    numeric: '616',
    shortName: 'Poland',
  },
  {
    alpha2: 'PM',
    alpha3: 'SPM',
    callingCodes: ['+508'],
    currencies: ['EUR'],
    emoji: '🇵🇲',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '666',
    shortName: 'Saint Pierre and Miquelon',
    territory: 'Miquelon',
  },
  {
    alpha2: 'PN',
    alpha3: 'PCN',
    callingCodes: ['+872'],
    currencies: ['NZD'],
    emoji: '🇵🇳',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '612',
    shortName: 'Pitcairn',
    territory: 'Ducie Island, Henderson Island, Oeno Island',
  },
  {
    alpha2: 'PR',
    alpha3: 'PRI',
    callingCodes: ['+1 787', '+1 939'],
    currencies: ['USD'],
    emoji: '🇵🇷',
    ioc: 'PUR',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '630',
    shortName: 'Puerto Rico',
  },
  {
    alpha2: 'PS',
    alpha3: 'PSE',
    callingCodes: ['+970'],
    currencies: ['JOD', 'EGP', 'ILS'],
    emoji: '🇵🇸',
    fullName: 'the State of Palestine',
    ioc: 'PLE',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '275',
    shortName: 'Palestine, State of',
  },
  {
    alpha2: 'PT',
    alpha3: 'PRT',
    callingCodes: ['+351'],
    currencies: ['EUR'],
    emoji: '🇵🇹',
    fullName: 'the Portuguese Republic',
    ioc: 'POR',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '620',
    shortName: 'Portugal',
  },
  {
    alpha2: 'PW',
    alpha3: 'PLW',
    callingCodes: ['+680'],
    currencies: ['USD'],
    emoji: '🇵🇼',
    fullName: 'the Republic of Palau',
    ioc: 'PLW',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: '',
        alpha3: 'pau',
      },
    ],
    numeric: '585',
    shortName: 'Palau',
    territory:
      'Babelthuap (principal island), the west part of the Caroline Islands',
  },
  {
    alpha2: 'PY',
    alpha3: 'PRY',
    callingCodes: ['+595'],
    currencies: ['PYG'],
    emoji: '🇵🇾',
    fullName: 'the Republic of Paraguay',
    ioc: 'PAR',
    languages: [
      {
        alpha2: 'gn',
        alpha3: 'grn',
      },
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '600',
    shortName: 'Paraguay',
  },
  {
    alpha2: 'QA',
    alpha3: 'QAT',
    callingCodes: ['+974'],
    currencies: ['QAR'],
    emoji: '🇶🇦',
    fullName: 'the State of Qatar',
    ioc: 'QAT',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '634',
    shortName: 'Qatar',
  },
  {
    alpha2: 'RE',
    alpha3: 'REU',
    callingCodes: ['+262'],
    currencies: ['EUR'],
    emoji: '🇷🇪',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '638',
    shortName: 'Réunion',
  },
  {
    alpha2: 'RO',
    alpha3: 'ROU',
    callingCodes: ['+40'],
    currencies: ['RON'],
    emoji: '🇷🇴',
    ioc: 'ROU',
    languages: [
      {
        alpha2: 'ro',
        alpha3: 'ron',
      },
    ],
    numeric: '642',
    shortName: 'Romania',
  },
  {
    alpha2: 'RS',
    alpha3: 'SRB',
    callingCodes: ['+381'],
    currencies: ['RSD'],
    emoji: '🇷🇸',
    fullName: 'the Republic of Serbia',
    ioc: 'SRB',
    languages: [
      {
        alpha2: 'sr',
        alpha3: 'srp',
      },
    ],
    numeric: '688',
    shortName: 'Serbia',
  },
  {
    alpha2: 'RU',
    alpha3: 'RUS',
    callingCodes: ['+7', '+7 3', '+7 4', '+7 8'],
    currencies: ['RUB'],
    emoji: '🇷🇺',
    fullName: 'the Russian Federation',
    ioc: 'RUS',
    languages: [
      {
        alpha2: 'ru',
        alpha3: 'rus',
      },
    ],
    numeric: '643',
    shortName: 'Russian Federation (the)',
    territory: 'Kaliningrad Region',
  },
  {
    alpha2: 'RW',
    alpha3: 'RWA',
    callingCodes: ['+250'],
    currencies: ['RWF'],
    emoji: '🇷🇼',
    fullName: 'the Republic of Rwanda',
    ioc: 'RWA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
      {
        alpha2: 'rw',
        alpha3: 'kin',
      },
    ],
    numeric: '646',
    shortName: 'Rwanda',
  },
  {
    alpha2: 'SA',
    alpha3: 'SAU',
    callingCodes: ['+966'],
    currencies: ['SAR'],
    emoji: '🇸🇦',
    fullName: 'the Kingdom of Saudi Arabia',
    ioc: 'KSA',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '682',
    shortName: 'Saudi Arabia',
  },
  {
    alpha2: 'SB',
    alpha3: 'SLB',
    callingCodes: ['+677'],
    currencies: ['SBD'],
    emoji: '🇸🇧',
    ioc: 'SOL',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '090',
    shortName: 'Solomon Islands',
    territory:
      'Guadalcanal (principal island), Southern Solomon Islands, Santa Cruz Islands',
  },
  {
    alpha2: 'SC',
    alpha3: 'SYC',
    callingCodes: ['+248'],
    currencies: ['SCR'],
    emoji: '🇸🇨',
    fullName: 'the Republic of Seychelles',
    ioc: 'SEY',
    languages: [
      {
        alpha2: '',
        alpha3: 'crs',
      },
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '690',
    shortName: 'Seychelles',
    territory:
      'Cosmoledo Islands, Farquhar Islands, Mahé (principal island), Aldabra Islands, Amirante Islands',
  },
  {
    alpha2: 'SD',
    alpha3: 'SDN',
    callingCodes: ['+249'],
    currencies: ['SDG'],
    emoji: '🇸🇩',
    fullName: 'the Republic of the Sudan',
    ioc: 'SUD',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '729',
    shortName: 'Sudan (the)',
  },
  {
    alpha2: 'SE',
    alpha3: 'SWE',
    callingCodes: ['+46'],
    currencies: ['SEK'],
    emoji: '🇸🇪',
    fullName: 'the Kingdom of Sweden',
    ioc: 'SWE',
    languages: [
      {
        alpha2: 'sv',
        alpha3: 'swe',
      },
    ],
    numeric: '752',
    shortName: 'Sweden',
  },
  {
    alpha2: 'SG',
    alpha3: 'SGP',
    callingCodes: ['+65'],
    currencies: ['SGD'],
    emoji: '🇸🇬',
    fullName: 'the Republic of Singapore',
    ioc: 'SIN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ms',
        alpha3: 'msa',
      },
      {
        alpha2: 'ta',
        alpha3: 'tam',
      },
      {
        alpha2: 'zh',
        alpha3: 'zho',
      },
    ],
    numeric: '702',
    shortName: 'Singapore',
  },
  {
    alpha2: 'SH',
    alpha3: 'SHN',
    callingCodes: ['+290'],
    currencies: ['SHP'],
    emoji: '🇸🇭',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '654',
    shortName: 'Saint Helena, Ascension and Tristan da Cunha',
    territory:
      'Ascension Island, Gough Island, Inaccessible Island, Nightingale Island, Saint Helena Island, Stoltenhoff Island, Tristan da Cunha Archipelago',
  },
  {
    alpha2: 'SI',
    alpha3: 'SVN',
    callingCodes: ['+386'],
    currencies: ['EUR'],
    emoji: '🇸🇮',
    fullName: 'the Republic of Slovenia',
    ioc: 'SLO',
    languages: [
      {
        alpha2: 'sl',
        alpha3: 'slv',
      },
    ],
    numeric: '705',
    shortName: 'Slovenia',
  },
  {
    alpha2: 'SJ',
    alpha3: 'SJM',
    callingCodes: ['+47'],
    currencies: ['NOK'],
    emoji: '🇸🇯',
    languages: [
      {
        alpha2: 'nn',
        alpha3: 'nno',
      },
      {
        alpha2: 'nb',
        alpha3: 'nob',
      },
    ],
    numeric: '744',
    shortName: 'Svalbard and Jan Mayen',
    territory: 'Bear Island, Jan Mayen',
  },
  {
    alpha2: 'SK',
    alpha3: 'SVK',
    callingCodes: ['+421'],
    currencies: ['EUR'],
    emoji: '🇸🇰',
    fullName: 'the Slovak Republic',
    ioc: 'SVK',
    languages: [
      {
        alpha2: 'sk',
        alpha3: 'slk',
      },
    ],
    numeric: '703',
    shortName: 'Slovakia',
  },
  {
    alpha2: 'SL',
    alpha3: 'SLE',
    callingCodes: ['+232'],
    currencies: ['SLL'],
    emoji: '🇸🇱',
    fullName: 'the Republic of Sierra Leone',
    ioc: 'SLE',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '694',
    shortName: 'Sierra Leone',
  },
  {
    alpha2: 'SM',
    alpha3: 'SMR',
    callingCodes: ['+378'],
    currencies: ['EUR'],
    emoji: '🇸🇲',
    fullName: 'the Republic of San Marino',
    ioc: 'SMR',
    languages: [
      {
        alpha2: 'it',
        alpha3: 'ita',
      },
    ],
    numeric: '674',
    shortName: 'San Marino',
  },
  {
    alpha2: 'SN',
    alpha3: 'SEN',
    callingCodes: ['+221'],
    currencies: ['XOF'],
    emoji: '🇸🇳',
    fullName: 'the Republic of Senegal',
    ioc: 'SEN',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '686',
    shortName: 'Senegal',
  },
  {
    alpha2: 'SO',
    alpha3: 'SOM',
    callingCodes: ['+252'],
    currencies: ['SOS'],
    emoji: '🇸🇴',
    fullName: 'the Federal Republic of Somalia',
    ioc: 'SOM',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'so',
        alpha3: 'som',
      },
    ],
    numeric: '706',
    shortName: 'Somalia',
  },
  {
    alpha2: 'SR',
    alpha3: 'SUR',
    callingCodes: ['+597'],
    currencies: ['SRD'],
    emoji: '🇸🇷',
    fullName: 'the Republic of Suriname',
    ioc: 'SUR',
    languages: [
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
    ],
    numeric: '740',
    shortName: 'Suriname',
  },
  {
    alpha2: 'SS',
    alpha3: 'SSD',
    callingCodes: ['+211'],
    currencies: ['SSP'],
    emoji: '🇸🇸',
    fullName: 'the Republic of South Sudan',
    ioc: 'SSD',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '728',
    shortName: 'South Sudan',
  },
  {
    alpha2: 'ST',
    alpha3: 'STP',
    callingCodes: ['+239'],
    currencies: ['STD'],
    emoji: '🇸🇹',
    fullName: 'the Democratic Republic of Sao Tome and Principe',
    ioc: 'STP',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
    ],
    numeric: '678',
    shortName: 'Sao Tome and Principe',
    territory: 'Principe',
  },
  {
    alpha2: 'SV',
    alpha3: 'SLV',
    callingCodes: ['+503'],
    currencies: ['USD'],
    emoji: '🇸🇻',
    fullName: 'the Republic of El Salvador',
    ioc: 'ESA',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '222',
    shortName: 'El Salvador',
  },
  {
    alpha2: 'SX',
    alpha3: 'SXM',
    callingCodes: ['+1 721'],
    currencies: ['ANG'],
    emoji: '🇸🇽',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'nl',
        alpha3: 'nld',
      },
    ],
    numeric: '534',
    shortName: 'Sint Maarten (Dutch part)',
  },
  {
    alpha2: 'SY',
    alpha3: 'SYR',
    callingCodes: ['+963'],
    currencies: ['SYP'],
    emoji: '🇸🇾',
    fullName: 'the Syrian Arab Republic',
    ioc: 'SYR',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '760',
    shortName: 'Syrian Arab Republic (the)',
  },
  {
    alpha2: 'SZ',
    alpha3: 'SWZ',
    callingCodes: ['+268'],
    currencies: ['SZL'],
    emoji: '🇸🇿',
    fullName: 'the Kingdom of Eswatini',
    ioc: 'SWZ',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'ss',
        alpha3: 'ssw',
      },
    ],
    numeric: '748',
    shortName: 'Eswatini',
  },
  {
    alpha2: 'TC',
    alpha3: 'TCA',
    callingCodes: ['+1 649'],
    currencies: ['USD'],
    emoji: '🇹🇨',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '796',
    shortName: 'Turks and Caicos Islands (the)',
    territory: 'Caicos Islands',
  },
  {
    alpha2: 'TD',
    alpha3: 'TCD',
    callingCodes: ['+235'],
    currencies: ['XAF'],
    emoji: '🇹🇩',
    fullName: 'the Republic of Chad',
    ioc: 'CHA',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '148',
    shortName: 'Chad',
  },
  {
    alpha2: 'TF',
    alpha3: 'ATF',
    currencies: ['EUR'],
    emoji: '🇹🇫',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '260',
    shortName: 'French Southern Territories (the)',
    territory:
      'Bassas da India, Crozet Archipelago, French scattered Indian Ocean Islands, Europa Island, Glorioso Islands, Juan de Nova Island, Kerguelen Islands, Saint-Paul Island, Tromelin Island, Amsterdam Island',
  },
  {
    alpha2: 'TG',
    alpha3: 'TGO',
    callingCodes: ['+228'],
    currencies: ['XOF'],
    emoji: '🇹🇬',
    fullName: 'the Togolese Republic',
    ioc: 'TOG',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '768',
    shortName: 'Togo',
  },
  {
    alpha2: 'TH',
    alpha3: 'THA',
    callingCodes: ['+66'],
    currencies: ['THB'],
    emoji: '🇹🇭',
    fullName: 'the Kingdom of Thailand',
    ioc: 'THA',
    languages: [
      {
        alpha2: 'th',
        alpha3: 'tha',
      },
    ],
    numeric: '764',
    shortName: 'Thailand',
  },
  {
    alpha2: 'TJ',
    alpha3: 'TJK',
    callingCodes: ['+992'],
    currencies: ['TJS'],
    emoji: '🇹🇯',
    fullName: 'the Republic of Tajikistan',
    ioc: 'TJK',
    languages: [
      {
        alpha2: 'tg',
        alpha3: 'tgk',
      },
    ],
    numeric: '762',
    shortName: 'Tajikistan',
  },
  {
    alpha2: 'TK',
    alpha3: 'TKL',
    callingCodes: ['+690'],
    currencies: ['NZD'],
    emoji: '🇹🇰',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: '',
        alpha3: 'tkl',
      },
    ],
    numeric: '772',
    shortName: 'Tokelau',
  },
  {
    alpha2: 'TL',
    alpha3: 'TLS',
    callingCodes: ['+670'],
    currencies: ['USD'],
    emoji: '🇹🇱',
    fullName: 'the Democratic Republic of Timor-Leste',
    ioc: 'TLS',
    languages: [
      {
        alpha2: 'pt',
        alpha3: 'por',
      },
      {
        alpha2: '',
        alpha3: 'tet',
      },
    ],
    numeric: '626',
    shortName: 'Timor-Leste',
    territory: 'the exclave of Oecussi',
  },
  {
    alpha2: 'TM',
    alpha3: 'TKM',
    callingCodes: ['+993'],
    currencies: ['TMT'],
    emoji: '🇹🇲',
    ioc: 'TKM',
    languages: [
      {
        alpha2: 'tk',
        alpha3: 'tuk',
      },
    ],
    numeric: '795',
    shortName: 'Turkmenistan',
  },
  {
    alpha2: 'TN',
    alpha3: 'TUN',
    callingCodes: ['+216'],
    currencies: ['TND'],
    emoji: '🇹🇳',
    fullName: 'the Republic of Tunisia',
    ioc: 'TUN',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '788',
    shortName: 'Tunisia',
  },
  {
    alpha2: 'TO',
    alpha3: 'TON',
    callingCodes: ['+676'],
    currencies: ['TOP'],
    emoji: '🇹🇴',
    fullName: 'the Kingdom of Tonga',
    ioc: 'TGA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'to',
        alpha3: 'ton',
      },
    ],
    numeric: '776',
    shortName: 'Tonga',
    territory: 'Tongatapu (principal island)',
  },
  {
    alpha2: 'TR',
    alpha3: 'TUR',
    callingCodes: ['+90'],
    currencies: ['TRY'],
    emoji: '🇹🇷',
    fullName: 'the Republic of Turkey',
    ioc: 'TUR',
    languages: [
      {
        alpha2: 'tr',
        alpha3: 'tur',
      },
    ],
    numeric: '792',
    shortName: 'Turkey',
  },
  {
    alpha2: 'TT',
    alpha3: 'TTO',
    callingCodes: ['+1 868'],
    currencies: ['TTD'],
    emoji: '🇹🇹',
    fullName: 'the Republic of Trinidad and Tobago',
    ioc: 'TTO',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '780',
    shortName: 'Trinidad and Tobago',
    territory: 'Tobago',
  },
  {
    alpha2: 'TV',
    alpha3: 'TUV',
    callingCodes: ['+688'],
    currencies: ['AUD'],
    emoji: '🇹🇻',
    ioc: 'TUV',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: '',
        alpha3: 'tvl',
      },
    ],
    numeric: '798',
    shortName: 'Tuvalu',
    territory: 'Funafuti (principal atoll)',
  },
  {
    alpha2: 'TW',
    alpha3: 'TWN',
    callingCodes: ['+886'],
    currencies: ['TWD'],
    emoji: '🇹🇼',
    ioc: 'TPE',
    languages: [
      {
        alpha2: 'zh',
        alpha3: 'zho',
      },
    ],
    numeric: '158',
    shortName: 'Taiwan (Province of China)',
    territory: 'Penghu (Pescadores) Islands',
  },
  {
    alpha2: 'TZ',
    alpha3: 'TZA',
    callingCodes: ['+255'],
    currencies: ['TZS'],
    emoji: '🇹🇿',
    fullName: 'the United Republic of Tanzania',
    ioc: 'TAN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'sw',
        alpha3: 'swa',
      },
    ],
    numeric: '834',
    shortName: 'Tanzania, the United Republic of',
  },
  {
    alpha2: 'UA',
    alpha3: 'UKR',
    callingCodes: ['+380'],
    currencies: ['UAH'],
    emoji: '🇺🇦',
    ioc: 'UKR',
    languages: [
      {
        alpha2: 'uk',
        alpha3: 'ukr',
      },
    ],
    numeric: '804',
    shortName: 'Ukraine',
  },
  {
    alpha2: 'UG',
    alpha3: 'UGA',
    callingCodes: ['+256'],
    currencies: ['UGX'],
    emoji: '🇺🇬',
    fullName: 'the Republic of Uganda',
    ioc: 'UGA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '800',
    shortName: 'Uganda',
  },
  {
    alpha2: 'UM',
    alpha3: 'UMI',
    callingCodes: ['+1'],
    currencies: ['USD'],
    emoji: '🇺🇲',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '581',
    shortName: 'United States Minor Outlying Islands (the)',
    territory:
      'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Navassa Island, Palmyra Atoll, Wake Island',
  },
  {
    alpha2: 'US',
    alpha3: 'USA',
    callingCodes: ['+1'],
    currencies: ['USD'],
    emoji: '🇺🇸',
    fullName: 'the United States of America',
    ioc: 'USA',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '840',
    shortName: 'United States of America (the)',
  },
  {
    alpha2: 'UY',
    alpha3: 'URY',
    callingCodes: ['+598'],
    currencies: ['UYU', 'UYI'],
    emoji: '🇺🇾',
    fullName: 'the Eastern Republic of Uruguay',
    ioc: 'URU',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '858',
    shortName: 'Uruguay',
  },
  {
    alpha2: 'UZ',
    alpha3: 'UZB',
    callingCodes: ['+998'],
    currencies: ['UZS'],
    emoji: '🇺🇿',
    fullName: 'the Republic of Uzbekistan',
    ioc: 'UZB',
    languages: [
      {
        alpha2: 'uz',
        alpha3: 'uzb',
      },
    ],
    numeric: '860',
    shortName: 'Uzbekistan',
  },
  {
    alpha2: 'VA',
    alpha3: 'VAT',
    callingCodes: ['+379', '+39'],
    currencies: ['EUR'],
    emoji: '🇻🇦',
    languages: [
      {
        alpha2: 'it',
        alpha3: 'ita',
      },
      {
        alpha2: 'la',
        alpha3: 'lat',
      },
    ],
    numeric: '336',
    shortName: 'Holy See (the)',
  },
  {
    alpha2: 'VC',
    alpha3: 'VCT',
    callingCodes: ['+1 784'],
    currencies: ['XCD'],
    emoji: '🇻🇨',
    ioc: 'VIN',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '670',
    shortName: 'Saint Vincent and the Grenadines',
    territory:
      'Bequia (principal island), Northern Grenadine Islands, Saint Vincent Island',
  },
  {
    alpha2: 'VE',
    alpha3: 'VEN',
    callingCodes: ['+58'],
    currencies: ['VEF'],
    emoji: '🇻🇪',
    fullName: 'the Bolivarian Republic of Venezuela',
    ioc: 'VEN',
    languages: [
      {
        alpha2: 'es',
        alpha3: 'spa',
      },
    ],
    numeric: '862',
    shortName: 'Venezuela (Bolivarian Republic of)',
    territory: 'Bird Island',
  },
  {
    alpha2: 'VG',
    alpha3: 'VGB',
    callingCodes: ['+1 284'],
    currencies: ['USD'],
    emoji: '🇻🇬',
    fullName: 'British Virgin Islands (the)',
    ioc: 'IVB',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '092',
    shortName: 'Virgin Islands (British)',
    territory: 'Anegada, Jost Van Dyke, Tortola, Virgin Gorda',
  },
  {
    alpha2: 'VI',
    alpha3: 'VIR',
    callingCodes: ['+1 340'],
    currencies: ['USD'],
    emoji: '🇻🇮',
    fullName: 'the Virgin Islands of the United States',
    ioc: 'ISV',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '850',
    shortName: 'Virgin Islands (U.S.)',
    territory: 'Saint Croix, Saint John, Saint Thomas',
  },
  {
    alpha2: 'VN',
    alpha3: 'VNM',
    callingCodes: ['+84'],
    currencies: ['VND'],
    emoji: '🇻🇳',
    fullName: 'the Socialist Republic of Viet Nam',
    ioc: 'VIE',
    languages: [
      {
        alpha2: 'vi',
        alpha3: 'vie',
      },
    ],
    numeric: '704',
    shortName: 'Viet Nam',
  },
  {
    alpha2: 'VU',
    alpha3: 'VUT',
    callingCodes: ['+678'],
    currencies: ['VUV'],
    emoji: '🇻🇺',
    fullName: 'the Republic of Vanuatu',
    ioc: 'VAN',
    languages: [
      {
        alpha2: 'bi',
        alpha3: 'bis',
      },
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '548',
    shortName: 'Vanuatu',
    territory: 'Efate, Santo',
  },
  {
    alpha2: 'WF',
    alpha3: 'WLF',
    callingCodes: ['+681'],
    currencies: ['XPF'],
    emoji: '🇼🇫',
    fullName: 'Wallis and Futuna Islands',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '876',
    shortName: 'Wallis and Futuna',
    territory: 'Futuna, Hoorn Islands, Uvea, Wallis Islands',
  },
  {
    alpha2: 'WS',
    alpha3: 'WSM',
    callingCodes: ['+685'],
    currencies: ['WST'],
    emoji: '🇼🇸',
    fullName: 'the Independent State of Samoa',
    ioc: 'SAM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'sm',
        alpha3: 'smo',
      },
    ],
    numeric: '882',
    shortName: 'Samoa',
    territory: "Savai'i, Upolu",
  },
  {
    alpha2: 'YE',
    alpha3: 'YEM',
    callingCodes: ['+967'],
    currencies: ['YER'],
    emoji: '🇾🇪',
    fullName: 'the Republic of Yemen',
    ioc: 'YEM',
    languages: [
      {
        alpha2: 'ar',
        alpha3: 'ara',
      },
    ],
    numeric: '887',
    shortName: 'Yemen',
    territory: 'Socotra Island',
  },
  {
    alpha2: 'YT',
    alpha3: 'MYT',
    callingCodes: ['+262'],
    currencies: ['EUR'],
    emoji: '🇾🇹',
    languages: [
      {
        alpha2: 'fr',
        alpha3: 'fra',
      },
    ],
    numeric: '175',
    shortName: 'Mayotte',
  },
  {
    alpha2: 'ZA',
    alpha3: 'ZAF',
    callingCodes: ['+27'],
    currencies: ['ZAR'],
    emoji: '🇿🇦',
    fullName: 'the Republic of South Africa',
    ioc: 'RSA',
    languages: [
      {
        alpha2: 'af',
        alpha3: 'afr',
      },
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
      {
        alpha2: 'nr',
        alpha3: 'nbl',
      },
      {
        alpha2: '',
        alpha3: 'nso',
      },
      {
        alpha2: 'st',
        alpha3: 'sot',
      },
      {
        alpha2: 'ss',
        alpha3: 'ssw',
      },
      {
        alpha2: 'tn',
        alpha3: 'tsn',
      },
      {
        alpha2: 'ts',
        alpha3: 'tso',
      },
      {
        alpha2: 've',
        alpha3: 'ven',
      },
      {
        alpha2: 'xh',
        alpha3: 'xho',
      },
      {
        alpha2: 'zu',
        alpha3: 'zul',
      },
    ],
    numeric: '710',
    shortName: 'South Africa',
    territory: 'Marion Island, Prince Edward Island',
  },
  {
    alpha2: 'ZM',
    alpha3: 'ZMB',
    callingCodes: ['+260'],
    currencies: ['ZMW'],
    emoji: '🇿🇲',
    fullName: 'the Republic of Zambia',
    ioc: 'ZAM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '894',
    shortName: 'Zambia',
  },
  {
    alpha2: 'ZW',
    alpha3: 'ZWE',
    callingCodes: ['+263'],
    currencies: ['USD', 'ZAR', 'BWP', 'GBP', 'EUR'],
    emoji: '🇿🇼',
    fullName: 'the Republic of Zimbabwe',
    ioc: 'ZIM',
    languages: [
      {
        alpha2: 'en',
        alpha3: 'eng',
      },
    ],
    numeric: '716',
    shortName: 'Zimbabwe',
  },
];
